### PR TITLE
Code formatting cleanup

### PR DESCRIPTION
**Pull request by alexgleith**
* Minor changes to code, like `var is True` rather than `var == True`.
* Changed to `isinstance(filepath, S3File)` rather than `type(filepath) == S3File` because my linter said that the latter wouldn't work (lead to unreachable code)

https://github.com/openjournals/joss-reviews/issues/7025#issuecomment-2297757431

### CODE REVIEW

**Comment by giswqs** [comment]
@alexgleith Thank you very much for the code cleanup. Some code blocks you pointed out were inherited from the [EMIT-Data-Resources](https://github.com/nasa/EMIT-Data-Resources/blob/main/python/modules/emit_tools.py#L347). I did not make changes. 

https://github.com/nasa/EMIT-Data-Resources/blob/main/python/modules/emit_tools.py#L347

image

You suggested changes look good except the following: 

`ortho = True` and `ortho = False` are intended for variable assignment, not conditional statements. So these need to be reverted. 
image

**Comment by alexgleith** [comment]
Whoops, sorry about that mistake @giswqs!

Ok, that makes sense re. the EMIT code.

I'm a bit uncomfortable with this section, as it's not very safe, but it makes more sense if it was just like that in the upstream source.

```python
    if longitude is not None and latitude is not None:
        ortho = True

    if downtrack is not None and crosstrack is not None:
        ortho = False
```

**Comment by giswqs** [comment]
The idea was to simplify the upstream in the [Exploring_EMIT_L2A_Reflectance.ipynb](https://github.com/nasa/EMIT-Data-Resources/blob/main/python/tutorials/Exploring_EMIT_L2A_Reflectance.ipynb) notebook code by creating the `plot_emit()` function that can plot both orthorectified and non-rothorectified EMIT data. If both `latitude` and `longitude` are set, we assume it is orthorectified data. Otherwise, if both `downtrack` and `crosstrack` are set, we assume it is non-orthorectified data. Would this be acceptable? I am open to suggestions for improving it.

**Review by giswqs — APPROVED** [review]

**Comment by giswqs** [comment]
I am merging this PR for now to avoid conflicts with a new PR also editing `emit.py`. I would be happy to improve this section if needed.

**Pull request merged**
